version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=sqs
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./aws:/docker-entrypoint-initaws.d"
